package consts

const (
	TableAppInfo                      = "ppm_bas_app_info"
	TableChangeLog                    = "ppm_bas_change_log"
	TableDctionary                    = "ppm_bas_dictionary"
	TableIssueTag                     = "ppm_pri_issue_tag"
	TableObjectId                     = "ppm_bas_object_id"
	TablePayLevel                     = "ppm_bas_pay_level"
	TableSourceChannel                = "ppm_bas_source_channel"
	TableOrganization                 = "ppm_org_organization"
	TableOrganizationOutInfo          = "ppm_org_organization_out_info"
	TableUser                         = "ppm_org_user"
	TableUserConfig                   = "ppm_org_user_config"
	TableUserOrganization             = "ppm_org_user_organization"
	TableUserOutInfo                  = "ppm_org_user_out_info"
	TableIssue                        = "ppm_pri_issue"
	TableIssueObjectType              = "ppm_prs_issue_object_type"
	TableIssueDetail                  = "ppm_pri_issue_detail"
	TableIssueRelation                = "ppm_pri_issue_relation"
	TableIteration                    = "ppm_pri_iteration"
	TableProject                      = "ppm_pro_project"
	TableProjectDetail                = "ppm_pro_project_detail"
	TableProjectRelation              = "ppm_pro_project_relation"
	TableProjectModule                = "ppm_pro_project_module"
	TableProjectVersion               = "ppm_pro_project_version"
	TableIssueSource                  = "ppm_prs_issue_source"
	TablePriority                     = "ppm_prs_priority"
	TableProcess                      = "ppm_prs_process"
	TableProcessProcessStatus         = "ppm_prs_process_process_status"
	TableProcessStatus                = "ppm_prs_process_status"
	TableProcessStep                  = "ppm_prs_process_step"
	TableProjectObjectType            = "ppm_prs_project_object_type"
	TableProjectObjectTypeProcess     = "ppm_prs_project_object_type_process"
	TableProjectType                  = "ppm_prs_project_type"
	TableProjectTypeProjectObjectType = "ppm_prs_project_type_project_object_type"
	TableResource                     = "ppm_res_resource"
	TableOperation                    = "ppm_rol_operation"
	TablePermission                   = "ppm_rol_permission"
	TablePermissionOperation          = "ppm_rol_permission_operation"
	TableRole                         = "ppm_rol_role"
	TableRoleOperation                = "ppm_rol_operation"
	TableRoleGroup                    = "ppm_rol_role_group"
	TableRolePermissionOperation      = "ppm_rol_role_permission_operation"
	TableRoleUser                     = "ppm_rol_role_user"
	TableShare                        = "ppm_sha_share"
	TableOrgConfig                    = "ppm_orc_config"
	TableMessageConfig                = "ppm_orc_message_config"
	TableMessage                      = "ppm_tak_message"
	TableTeam                         = "ppm_tem_team"
	TableUserTeam                     = "ppm_tem_user_team"
	TableComment                      = "ppm_tre_comment"
	TableTrends                       = "ppm_tre_trends"

	TableIterationStat  = "ppm_sta_iteration_stat"
	TableProjectDayStat = "ppm_sta_project_day_stat"

	TableMessageQueue             = "ppm_mqs_message_queue"
	TableMessageQueueConsumer     = "ppm_mqs_message_queue_consumer"
	TableMessageQueueConsumerFail = "ppm_mqs_message_queue_consumer_fail"
	TableDepartment               = "ppm_org_department"
	TableDepartmentOutInfo        = "ppm_org_department_out_info"
	TableUserDepartment           = "ppm_org_user_department"

	TableContact        = "ppm_wst_contact"
	TableTag            = "ppm_pri_tag"
	TableNotice         = "ppm_tre_notice"
	TableArea           = "ppm_cmm_area"
	TableCities         = "ppm_cmm_cities"
	TableContinents     = "ppm_cmm_continents"
	TableCountries      = "ppm_cmm_countries"
	TableIndustry       = "ppm_cmm_industry"
	TableMobilePrefix   = "ppm_cmm_area"
	TableRegions        = "ppm_cmm_regions"
	TableStates         = "ppm_cmm_states"
	TableFolder         = "ppm_res_folder"
	TableFolderResource = "ppm_res_folder_resource"
)
